#name, main, version and api are required
name: EntityManager
main: milk.entitymanager.EntityManager
#remember version and api is string, don't write it like this: 1.0.0, or there will be an exception
version: "3.0 Beta"
api: ["2.0.0"]

load: STARTUP
author: milk0417
description: control entity's movement
website: https://github.com/EntityManager
commands:
  entitymanager:
    description: control entity command
    aliases: ["entity", "ent"]
    usage: "/entitymanager <remove/spawn/check>"
    permission: entitymanager.command
permissions:
  entitymanager.command:
    description: ""
    default: op
